### ISSUE TITLE
Review del desafío

### ISSUE THREAD

**Issue by tobiasfacello** [EnriqueScianca/Desafio-mod3#2]
Hola Quique, primero que nada felicidades por haber finalizado el desafío del módulo 3!

Como observación general el desafío cumple con los requisitos para la aprobación como tal.

Detalles a tener en cuenta:
- Evitar el uso de números a la hora de asignar clases, no es algo recomendable. Aún así, el módulo que viene vas a ver buenas prácticas y metodologías (como lo es BEM, por si queres explorarlo de antemano).

En cuanto a lo demás, no tengo más que decir LGTM y mucho éxito en el próximo módulo!

**Comment by EnriqueScianca** [comment]
Hola Fache, gracias por el feedback. voy a tener en cuenta tus consejos y a pegarle una mirada a las cosas que me decís así voy adelantando con el curso. Saludos!!
